### ISSUE TITLE
Syntax error while running captcha_generator.py 

### ISSUE THREAD

**Issue by Alinahui** [zakizhou/CAPTCHA#1]
Traceback (most recent call last):
  File "CNN/captcha_generator.py", line 8, in <module>
    from captcha.image import ImageCaptcha
  File "/home/hui/Downloads/CAPTCHA-master/CNN/captcha.py", line 20
    tf.constant_initializer(value=0),
                               ^
SyntaxError: positional argument follows keyword argument
you import  "from captcha.image import ImageCaptcha", but it is not found in CAPTCHA.py, is it a separate module then where to import ImageCAPTCHA module?

**Comment by zakizhou** [comment]
Yes, captcha is a separate module in Python, you can simply use pip to install it

**Comment by Alinahui** [comment]
ok thanks for your response i will try it

**Comment by Alinahui** [comment]
i have used pip to install CAPTCHA and it is installed successfully however still following error occoured
python CNN/captcha_generator.py -n 50000 -p "~/images/"
Traceback (most recent call last):
  File "CNN/captcha_generator.py", line 8, in <module>
    from captcha.image import ImageCaptcha
ImportError: No module named 'captcha.image'; 'captcha' is not a package

**Comment by zakizhou** [comment]
Have you intalled it using
`
sudo pip install captcha
`?
I didn't have any problem when importing
![captcha](https://cloud.githubusercontent.com/assets/19201532/20166152/de92ee5e-a74d-11e6-868e-ce95c9585d71.png)

**Comment by Alinahui** [comment]
no i directly installed it using pip install captcha
but now i have installed it again by using your method "sudo pip install captcha"
but it is still not working and giving the same error

**Comment by zakizhou** [comment]
Do you create a virtual machine of Python? The python you used to run this script is the one you installed this packages?

**Comment by Alinahui** [comment]
thanks it seems to be working now

**Comment by Alinahui** [comment]
thanks, successfully generated 50,000 training and 10,000 images however found following error while running captca_train.py :
Traceback (most recent call last):
  File "captcha_train.py", line 34, in <module>
    main()
  File "captcha_train.py", line 13, in main
    images, labels = captcha_inputs.inputs("/home/hui/abc2/images/", 5, 100, 300)
  File "/home/hui/abc2/CNN/captcha_inputs.py", line 32, in inputs
    image, label = read_and_decode(path)
  File "/home/hui/abc2/CNN/captcha_inputs.py", line 14, in read_and_decode
    filename_tensor = tf.convert_to_tensor(filenames)
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 657, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 422, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 422, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/hui/.local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 64, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got map object at 0x7f9456eb9390

**Comment by Alinahui** [comment]
TypeError: Expected binary or unicode string, got <map object at 0x7fa81f45d390>

**Comment by zakizhou** [comment]
I am perfecting  the training script these days and will soon update it, I'm afraid you'd need to wait for two days if you still want to train a deep learning captcha model using my code.
I peronsally recommend you to use the code  and follow the tutorial [here](https://matthewearl.github.io/2016/05/06/cnn-anpr/) 
BTW, is python3.5 stable for machine learning?

**Comment by Alinahui** [comment]
ok thanks

**Comment by Alinahui** [comment]
[here](https://matthewearl.github.io/2016/05/06/cnn-anpr/)

**Comment by Alinahui** [comment]
Hi ! zakizhou,  have you finished your testing on this code for CAPTCHAS ? i am still confused in the above mentioned tutorial by Matthew Earl, can you help me in this regard?

**Comment by zakizhou** [comment]
@Alinahui I'm so sorry it's approching final now so I'm busy with my lessons like measure theory and mathmatical statisics and don't have much time to write code. Last night I finished the whole captcha project and you can now run it, for more details see readme
