### ISSUE TITLE
How much Accuracy is achieved?

### ISSUE THREAD

**Issue by Zaibjee** [zakizhou/CAPTCHA#2]
Hi zakizhou
This is a wonderful work, i would like to know that how much accuracy you have achieved on your model?

**Comment by zakizhou** [comment]
Thank you and sorry to be late, I trained it in single tesla K20m for 40 minutes, and reached a peak accuracy about 86% on validation set, adding dropout or increasing the scale of parameters should still improve the accuracy.

**Comment by Zaibjee** [comment]
ok and thanks for your reply

**Comment by Zaibjee** [comment]
Zakizhou can you kindly help in this regard:
The following error occurred while running:    python model/captcha_producer.py -n 50000 -p "images/train"

Traceback (most recent call last):
  File "model/captcha_producer.py", line 39, in <module>
    main()
  File "model/captcha_producer.py", line 35, in main
    producer.write(number_to_write, os.path.join(path, str(i)+"_"+number_to_write+".png"))
  File "/home/zaib/.local/lib/python3.5/site-packages/captcha/image.py", line 53, in write
    im = self.generate_image(chars)
  File "/home/zaib/.local/lib/python3.5/site-packages/captcha/image.py", line 220, in generate_image
    self.create_noise_curve(im, color)
  File "/home/zaib/.local/lib/python3.5/site-packages/captcha/image.py", line 127, in create_noise_curve
    y1 = random.randint(h / 5, h - int(h / 5))
  File "/home/zaib/anaconda3/lib/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/home/zaib/anaconda3/lib/python3.5/random.py", line 182, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by zakizhou** [comment]
@Zaibjee Sorry I'm afraid I don't have time right now to fix this bug, it ran normally on my PC. But I have already converted training and validation images to tfrecords, but I don't know how to share those files with others,  maybe upload  to some cloud storage? If you need it, I can send it to you with email(leave you email here), then you can directly train this model without manually generating data.

**Comment by Zaibjee** [comment]
my email address is zaibshah889@yahoo.com
thanks

**Comment by zakizhou** [comment]
@Zaibjee already sent , about 350M, uncompress it you get two tfrecords file namely train.tfrecords and validation.tfrecords, put them in the images/tfrecords/ folder and then you can run the training part

**Comment by Zaibjee** [comment]
thanks a lot @zakizhou

**Comment by zakizhou** [comment]
@Zaibjee wait, there's some error with the email server, I am trying to resend

**Comment by Zaibjee** [comment]
alright @zakizhou

**Comment by zakizhou** [comment]
@Zaibjee done

**Comment by Zaibjee** [comment]
thanks for your time and help @zakizhou

**Comment by samirma** [comment]
Hello @zakizhou 
Could you send it to me too? 
That is my email: samir.ma@gmail.com

Thanks

**Comment by santoja** [comment]
I fixed the "ValueError: non-integer arg 1 for randrange()" Error.
